name: Render and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  convert-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("jsonlite", "stringr"))'

      - name: Convert README to JSON
        run: Rscript convert_to_json.R

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: json-data
          path: readme_data.json
          retention-days: 1

  render-and-deploy:
    needs: convert-to-json
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: json-data
          
      - name: Render dashboard
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: index.Rmd
          output_format: flexdashboard::flex_dashboard

      - name: Create dist directory
        run: |
          mkdir -p dist
          cp index.html dist/
          cp readme_data.json dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 